baseurl = "https://aleixalcacer.github.io/hugo-portfolio/"
title = "Aleix Alcacer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true

[params]
  author = "Aleix Alcacer"
  info = "Open Source Contributor | Systems Analyst | PhD in Mathematics"
  description = "Aleix Alcacer's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2020

  math = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
  
# Social links

[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:aleixalcacer@gmail.com"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/aleixalcacer/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/aleixalcacer/"


# Menu links

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

          [[menu.main]]
            name = "Blog"
            weight = 2
            url  = "posts/"

          [[menu.main]]
            name = "Projects"
            weight = 3
            url  = "projects/"

          [[menu.main]]
          name = "About"
          weight = 5
          url = "about/"
          